export const itemParams = {
  strength: 'сила',
  agility: 'ловкость',
  intelligence: 'разум',
  attack: 'урон',
  defence: 'защита',
  visibility: 'обзор',
  luck: 'удача',
  hp: 'ХП',
  mp: 'МП',
  resist: 'сопротивление магии',
  hp_regeneration: 'регенерация здоровья',
  mp_regeneration: 'регенерация маны', // %
  mp_regen: 'регенерация маны',
  stealth_detection: 'обнаружение невидимок',
  as: 'скорость атаки',
  ms: 'скорость бега',
  manaburn: 'каждый удар сжигает',
  evade: 'уклонение',
  aura: 'аура',
  active: 'актив',
  distant_resist: 'снижение урона',
  critical_chance: 'шанс крита:',
  block_chance: 'шанс блока:',
}
